# Generated by Django 3.2.9 on 2022-01-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=10)),
                ('details', models.CharField(default='We are great at what we do!', max_length=100)),
                ('total_slots', models.IntegerField(default=0)),
            ],
        ),
    ]
