# Generated by Django 3.2.9 on 2022-01-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider_login', '0003_alter_servicecreds_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecreds',
            name='image',
        ),
    ]
