# Generated by Django 3.2.9 on 2022-01-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider_login', '0006_remove_servicecreds_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecreds',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
