# Generated by Django 3.2.9 on 2022-01-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider_login', '0009_auto_20220106_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecreds',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
