# Generated by Django 3.2.9 on 2022-01-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginCreds',
        ),
    ]
