# Generated by Django 3.2.9 on 2022-01-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientLogin', '0002_auto_20220104_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumercreds',
            old_name='user_name',
            new_name='username',
        ),
    ]
