# Generated by Django 3.2.9 on 2022-01-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientLogin', '0004_auto_20220105_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCreds',
        ),
    ]
